lauguages:
  Ruby: false
  Javascript: true
ratings: # customize
  paths:
  - app/**/*
  - lib/**/*
exclude_paths: # customize
- .bundle/
- app/assets/fonts/
- app/assets/images/
- app/assets/javascripts/vendor/
- app/assets/stylesheets/vendor/
- bin/rails
- bin/rake
- db/
- doc/
- files/
- public/
- spec/
- tmp/
- tests/
